<a href="https://colab.research.google.com/github/IdaSharonJ/Python-exercises/blob/main/24AUG_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Exercise 1

* Generate a 1D numpy array with the values [7, 9, 65, 33, 85, 99]

* Generate a matrix (2D numpy array) of the values:

\begin{align}
  \mathbf{A} =
  \begin{pmatrix}
    1 & 2 & 4 \\
    2 & 3 & 0 \\
    0 & 5 & 1
  \end{pmatrix}
\end{align}

* Change the dimensions of this array to another permitted shape

In [15]:
import numpy as np

In [11]:
ar_one = [7,9,65,33,85,99]
print(ar_one)

[7, 9, 65, 33, 85, 99]


In [12]:
new = np.array(ar_one)
print(type(new))
print(new)

<class 'numpy.ndarray'>
[ 7  9 65 33 85 99]


In [18]:
a = np.array([1,2,4,2,3,0,0,5,1,])
new = a.reshape(3, 3)
print(new)

[[1 2 4]
 [2 3 0]
 [0 5 1]]


In [19]:
newon = new.reshape(3, 1, 3)
print(newon)

[[[1 2 4]]

 [[2 3 0]]

 [[0 5 1]]]


### Exercise 2

* #### Create an array of string numbers, but use dtype to make it an array of floats.
* #### Transpose the matrix, printing the new size and shape.
* #### Use the .astype() method to convert the array to boolean.

In [21]:
arr = np.array([['1','2','3'],['4','5','6']])
arr.dtype

dtype('<U1')

In [22]:
new_arr = arr.astype('float64')
print(new_arr)

[[1. 2. 3.]
 [4. 5. 6.]]


In [24]:
a.shape = (3,3)
print(a, "\n")
print(a.T)

[[1 2 4]
 [2 3 0]
 [0 5 1]] 

[[1 2 0]
 [2 3 5]
 [4 0 1]]


In [26]:
Booleanmat=np.array(a,dtype=bool)
print(Booleanmat)

[[ True  True  True]
 [ True  True False]
 [False  True  True]]


### Exercise 3

* Create a numpy array with 50 zeros
* Create a np array of 2 repeated 20 times
* Create a numpy array from 0 to 2 $\pi$ in steps of 0.1

For one of the arrays generated:
* Get the first five values
* Get the last 3 values
* Get the 4th value to the 7th value

In [28]:
zeroarr=np.zeros(50)
print(zeroarr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [29]:
zeroarr[0:5]

array([0., 0., 0., 0., 0.])

In [30]:
abc = np.repeat(2,20)
print(abc)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [32]:
abc[-3:]

array([2, 2, 2])

In [35]:
import math
matharr = np.arange(0,2*(math.pi),0.1)
matharr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2])

In [37]:
matharr[4:8]

array([0.4, 0.5, 0.6, 0.7])

### Exercise 4
Take one of the arrays you defined and
* #### Reverse it
* #### Only keep every 4th element.
* #### Get every 2nd element, starting from the last and moving backwards.

In [41]:
fivetable = np.arange(0, 55, 5)
fivetable

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [42]:
revtable = np.flip(fivetable)
revtable

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [44]:
revtable[0::4]

array([50, 30, 10])

In [45]:
revtable[::-2]

array([ 0, 10, 20, 30, 40, 50])

### Exercise 5

* Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.

In [46]:
nums = np.arange(0, 4, 0.2555)
nums

array([0.    , 0.2555, 0.511 , 0.7665, 1.022 , 1.2775, 1.533 , 1.7885,
       2.044 , 2.2995, 2.555 , 2.8105, 3.066 , 3.3215, 3.577 , 3.8325])

In [47]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


### Exercise 6
* Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws.
* Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.


In [48]:
toss = np.random.choice(list(range(1,7)),10)
toss

array([3, 4, 2, 2, 3, 1, 4, 5, 3, 5])

In [49]:
coinflip = np.random.choice([0,1,1],10)
coinflip

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 0])